album/urls.py
from django.urls import path
from . import views

app_name = "album"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:album_id>/', views.detail, name="detail"),
]

eng/urls.py
from django.contrib import admin
from core import views as core
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core.index, name="home"),
    path('introducing/', core.introducing, name="introducing"),
]
urlpatterns += i18n_patterns(
    path('introducing/', core.introducing, name="introducing"),
    path('contact/', core.contact, name="contact"),
    path('managers/', core.managers, name="managers"),
    path('labs/', core.labs, name="labs"),
    path('group/', include('groups.urls')),
    path('fields/', include('fields.urls')),
    path('staff/', include('staff.urls')),
    path('album/', include('album.urls')),
    path('news/', include('news.urls')),
)


if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.error404'
handler500 = 'core.views.error500'

fields/urls.py
from django.urls import path
from . import views

app_name = "fields"
urlpatterns = [
    path('', views.index, name="index"),
    path('<str:degree_slug>/', views.degree_detail, name="degree_detail"),
    path('<str:degree_slug>/<str:field_slug>/', views.field_detail, name="field_detail"),
]

groups/urls.py
from django.urls import path
from . import views

app_name = "groups"
urlpatterns = [
    path('', views.index, name="index"),
    path('<slug:slug>/', views.group_detail, name="detail"),
]

news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    path('', views.index, name="index"),
    path('<str:title>/', views.detail, name="detail"),
]

staff/urls.py
from django.urls import path
from . import views

app_name = "staff"
urlpatterns = [
    path('', views.index, name="index"),
]

album/models.py
from django.db import models

def album_image_path(instance, filename):
    return 'album/{0}/{1}'.format(instance.album.pk, filename)

class Album(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(allow_unicode=True)
    
    class Meta:
        verbose_name = "آلبوم"
        verbose_name_plural = "آلبوم‌ها"

    def __str__(self):
        return str(self.pk)

class AlbumImage(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=album_image_path)
    caption = models.CharField(max_length=50)

    class Meta:
        verbose_name = "AlbumImage"
        verbose_name_plural = "AlbumImages"

    def __str__(self):
        return str(self.pk)

core/models.py
from django.db import models

# Create your models here.

fields/models.py
from django.db import models
from django.urls import reverse

class Field(models.Model):
    degree = models.ForeignKey("fields.Degree", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(allow_unicode=True)

    class Meta:
        verbose_name = "Field"
        verbose_name_plural = "Fields"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Field_detail", kwargs={"pk": self.pk})

class Degree(models.Model):

    name = models.CharField(max_length=50)
    slug = models.SlugField()

    class Meta:
        verbose_name = "Degree"
        verbose_name_plural = "Degrees"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Degree_detail", kwargs={"pk": self.pk})

groups/models.py
from django.db import models
from django.urls import reverse

class Group(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    class Meta:
        verbose_name = "گروه"
        verbose_name_plural = "گروه ها"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("groups:group", kwargs={"pk": self.pk})

news/models.py
from django.db import models
from django.urls import reverse

class News(models.Model):
    title = models.CharField(max_length=125)
    content = models.TextField()

    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True, auto_now=True)
    

    class Meta:
        verbose_name = "خبر"
        verbose_name_plural = "اخبار"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news_detail", kwargs={"pk": self.pk})

staff/models.py
from django.db import models

class Staff(models.Model):
    name = models.CharField(max_length=75)
    local_phone_number = models.IntegerField()
    position = models.CharField(max_length=150)
    room_location = models.CharField(max_length=100)
    
    class Meta:
        verbose_name = "کارکنان"
        verbose_name_plural = "کارکنان"

    def __str__(self):
        return self.name

album/views.py
from django.shortcuts import render
from .models import Album

def index(request):
    albums = Album.objects.all()
    context={
        'albums':albums,
    }
    return render(request, 'album/index.html', context)

def detail(request, album_id):
    album = Album.objects.get(pk=album_id)
    context={
        'album':album,
    }
    return render(request, 'album/detail.html', context)

core/views.py
from django.shortcuts import render
from news.models import News

def index(request):
    news = News.objects.all()[:3]
    context={
        'news':news,
    }
    return render(request, 'index.html', context)

def introducing(request):
    return render(request, 'pages/introducing.html', {})

def contact(request):
    return render(request, 'pages/contact.html', {})

def managers(request):
    return render(request, 'pages/managers.html', {})

def labs(request):
    return render(request, 'pages/labs.html', {})

def error404(request, exception):
    return render(request, 'pages/error404.html', context={}, status=404)
    
def error500(request):
    return render(request, 'pages/error500.html', context={})

fields/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Degree, Field

def index(request):
    degrees = Degree.objects.all()
    context = {
        'degrees':degrees,
    }
    return render(request, 'fields/index.html', context)

def degree_detail(request, degree_slug):
    degree = Degree.objects.get(slug=degree_slug)
    context = {
        'degree':degree,
    }
    return render(request, 'fields/degree_detail.html', context)

def field_detail(request, degree_slug, field_slug):
    if field_slug.endswith('/'):
        field_slug=field_slug[:-1]
    degree = get_object_or_404(Degree, slug=degree_slug)
    field = get_object_or_404(Field, degree=degree, slug=field_slug)
    context = {
        'degree':degree,
        'field':field,
    }
    return render(request, 'fields/field_detail.html', context)

groups/views.py
from django.shortcuts import render, get_object_or_404
from .models import Group

def index(request):
    groups = Group.objects.all()
    context = {
        'groups':groups,
    }
    return render(request, 'groups/index.html', context)

def group_detail(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group':group,
    }
    return render(request, 'groups/detail.html', context)

news/views.py
from django.shortcuts import render, get_object_or_404
from .models import News

def index(request):
    news = News.objects.all()
    context = {
        'news':news,
    }
    return render(request, 'news/index.html', context)

def detail(request, title):
    news = get_object_or_404(News, title=title)
    context = {
        'news':news,
    }
    return render(request, 'news/detail.html', context)

staff/views.py
from django.shortcuts import render
from .models import Staff
from django.core.paginator import Paginator

def index(request):
    staff_list = Staff.objects.all()
    staff_count = staff_list.count()
    paginator = Paginator(staff_list, 10)
    page_number = request.GET.get('page')
    staff = paginator.get_page(page_number)
    context ={
        'staff':staff,
        'staff_count':staff_count,
    }
    return render(request, 'staff/index.html', context)

templates/album/detail.html
{% extends 'shared/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">صفحه‌اصلی</a></li>
                <li><a href="{% url 'album:index' %}">دسته های گالری تصاویر</a></li>
                <li class="active">دانشکده برق و کامپیوتر</li>
            </ul>
        </div>
    </div>
</div>
<div class="container main-content">
    <div class="row">
        <div class="col-xs-12 col-sm-9 pull-right flip">

            <div class="album-view">
                <h1 class="page-title">
                    دانشکده برق و کامپیوتر </h1>
                <article class="album">
                    <div class="meta-info album-info">
                        <span class="label label-default">
                            ۰۵ مهر ۱۳۹۴ </span>
                        <span class="label label-default">
                            <i class="fa fa-camera-retro"></i>
                            ۹ </span>
                    </div>
                    <div id="shots" class="shots clearfix">
                        <div class="row gutter-4">
                            {% for image in album.albumimage_set.all %}
                            <div class="col-xs-4 col-sm-3 col-md-2">
                                <div class="thumbnail">
                                    <a class="image-link"
                                        href="{{image.image.url}}"
                                        title="{{image.title}}"><img class="img-responsive"
                                            src="{{image.image.url}}"
                                            width="360" height="200" alt="{{image.title}}"
                                            data-description="{{image.title}}"></a> </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </article>
            </div>

        </div>
        <aside class="col-xs-12 col-sm-3 pull-left flip">
            <div>

                <div class="albums-list-widget categories-widget ">
                    <ul class="gallery-albums-list list-unstyled">
                        <li>
                            <div class="thumb-wrapper">
                                <a
                                    href="{% url 'album:detail' album.pk %}"><img
                                        class="img-responsive"
                                        src="{% for image in album.albumimage_set.all %}{% if forloop.first %}{{image.image.url}}{% endif %}{% endfor %}"
                                        width="800" height="600" alt="{{album.name}}"></a> </div>
                            <div class="content-wrapper">
                                <h4 class="album-item-title">
                                    <a
                                        href="{% url 'album:detail' album.pk %}">{{album.name}}</a> </h4>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </aside>
    </div>
</div>
{% endblock body %}

templates/album/index.html
{% extends 'shared/base.html' %} {% block body %}
<div class="container main-content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 pull-left flip">
            <div class="albums-view container">
                <div class="row no-gutter">
                    <section id="wbe0e7ea7326ed19fd327327f1f1937be0" class="albums-wrapper clearfix">
                        {% for album in albums %}
                        <div class="item col-sm-4 col-md-3" data-key="65">
                            <div class="thumbnail">
                                <a href="{% url 'album:detail' album.pk %}">
                                    <img class="img-responsive" src="{% for image in album.albumimage_set.all %}{% if forloop.first %}{{image.image.url}}{% endif %}{% endfor %}" width="800" height="600" alt="دانشکده برق و کامپیوتر">
                                        <small class="images-count">{{album.albumimage_set.count}} <i class="fa fa-camera-retro"></i></small></a>
                                <div class="caption">
                                    <h3 class="title">
                                        <a href="{% url 'album:detail' album.pk %}">{{album.name}}</a> </h3>
                                    <p>
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/groups/index.html
{% extends 'shared/base.html' %}
{% load static %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">صفحه‌اصلی</a></li>
                <li class="active">گروه ها</li>
            </ul>
        </div>
    </div>
</div>
<div class="container main-content">
    <div class="row">
        <div class="col-xs-12 col-sm-9 pull-right flip">
            <div class="page-view article-view">
                <article>
                    <h1>گروه ها</h1>
                    <figure>
                    </figure>
                    <div class="content">
                    </div>
                </article>
                <hr class="seprator">
                <div class="nestedpage-widget widget">
                    <ul class="list-unstyled">
                        {% for group in groups %}
                        <li>
                            <a href="{% url 'groups:detail' group.slug %}"><i class="fa fa-angle-right"></i> مهندسی
                                {{group.name}}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div style="clear:both;"></div>
            </div>
        </div>
        <aside class="col-xs-12 col-sm-3 pull-left flip">
            <div class="nestedpage-widget widget side-menu">

                <h4 class="">
                    صفحات مرتبط </h4>

                <ul class="list-unstyled">
                    <li class="active parent">
                        - گروه ها </li>
                    {% for group in groups %}
                    <li>
                        <a
                            href="{% url 'groups:detail' group.slug %}">-
                            {{group.name}}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </aside>
    </div>
</div>
{% endblock body %}

templates/news/detail.html
{% extends 'shared/base.html' %}
{% load static %}
{% block title %}{{news.title}}{% endblock title %}

{% block body %}
<div class="grey lighten-4">
    <div class="container">
        <div dir="rtl" class="row pt-5 mt-5 text-right">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">صفحه‌اصلی</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'news:index' %}">اخبار</a></li>
                    <li class="breadcrumb-item active">{{news.pk}}</li>
                  </ol>
                </nav>
            </div>
        </div>
    </div>
    <div class="container">
        <div dir="rtl" class="row text-right">
            <div class="col-12">
                <div class="card hoverable my-5">
                    <div class="card-body">
                        <h4 class="card-title">{{news.title}}</h4>
                        <hr class="my-3">
                        <p class="card-text lead">
                            
                            {{news.content|linebreaks}}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/news/index.html
{% extends 'shared/base.html' %}
{% load static %}
{% block title %}اخبار{% endblock title %}

{% block body %}
<div class="grey lighten-4">
    <div class="container">
        <div dir="rtl" class="row pt-5 mt-5 text-right">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">صفحه‌اصلی</a></li>
                    <li class="breadcrumb-item active">اخبار</li>
                  </ol>
                </nav>
            </div>
        </div>
    </div>
    <div class="container">
        <div dir="rtl" class="row text-right">
            {% for n in news %}
            <div class="col-12 col-md-6 col-lg-4 my-3">
                <div class="card hoverable">
                    <a href="{% url 'news:detail' n.title %}" class="text-dark">
                        <div class="card-body">
                            <p class="card-title">{{n.title}}</p>
                        </div>
                        <div class="card-footer">
                            {{n.created_at}}
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body %}

templates/shared/footer.html
<footer class="page-footer font-small unique-color-dark">
  <div class="container text-center text-md-left py-3">
    <div dir="rtl"  class="row mt-3 text-right">
      <div class="col-12 col-md-6 col-lg-6 mx-auto mb-4 ">
        <h6 class="text-uppercase font-weight-bold">ارتباط</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto w-75">
        <p>
          <i class="fas fa-home mr-3"></i> تهران -بزرگراه شهید بابایی (غرب به شرق)- خروجی حکیمیه- خیابان شهید صدوقی- بلوار شهید عباسپور- دانشگاه آزاد اسلامی واحد تهران شمال</p>
        <p>
          <i class="fas fa-phone mr-3"></i> <span dir="ltr">+98 21 77 00 98 00</span></p>

      </div>
      <div class="col-12 col-md-3 col-lg-3 mx-auto mb-4">
        <h6 class="text-uppercase font-weight-bold">لینک های مفید</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="{% url 'introducing' %}">معرفی دانشکده</a>
        </p>
        <p>
          <a href="{% url 'groups:index' %}">گروه های آموزشی</a>
        </p>
        <p>
          <a href="{% url 'staff:index' %}">کارکنان</a>
        </p>
        <p>
          <a href="{% url 'fields:index' %}">رشته های تحصیلی</a>
        </p>
      </div>
      <div class="col-12 col-md-3 col-lg-3 mx-auto mb-4">
        <h6 class="text-uppercase font-weight-bold">دسترسی</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="{% url 'album:index' %}">آلبوم تصاویر</a>
        </p>
        <p>
          <a href="http://iau-tnb.ac.ir/fa/regulation">فرم ها و آئین نامه ها</a>
        </p>
        <p>
          <a href="{% url 'news:index' %}">اخبار دانشکده</a>
        </p>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-3">
    <div dir="rtl" class="container-fluid">
      <div class="row">
        <div class="col-12 col-md-4 col-lg-5">
            <a class="mx-3" href="{% url 'contact' %}" target="_self"> تماس با ما</a>
            <a class="mx-3" href="{% url 'contact' %}" target="_self"> دفتر تلفن</a>
        </div>
        <div class="col-12 col-md-8 col-lg-7">
            © کلیه حقوق متعلق به دانشگاه آزاد اسلامی واحد تهران شمال می‌باشد.
            <a href="https://mdbootstrap.com/"></a>
        </div>
      </div>
    </div>

  </div>
</footer>
{% comment %} <footer>
    <div class="container">
        <div>
            <div class="menu-widget-simple widget ">
                <ul class="list-inline footer-menu divider-list left">
                    <li>
                        <a class=" " href="{% url 'contact' %}" target="_self"> تماس با ما</a>
                    </li>
                    <li>
                        <a class=" " href="{% url 'contact' %}" target="_self"> دفتر تلفن</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row copyright">
            <div class="copyright-container">
                © کلیه حقوق متعلق به دانشگاه آزاد اسلامی واحد تهران شمال می‌باشد.
            </div>
        </div>
    </div>
</footer> {% endcomment %}

templates/shared/header.html
{% load static %}

<header>

  <nav class="stylish-color text-white text-right py-1">
    <div class="container">
        <div dir="rtl" class="row">
            <div class="col-12 col-md-8">    
                <small class="text-small">
                    به وب سایت دانشکده برق و کامپیوتر دانشگاه آزاد اسلامی واحد تهران شمال خوش آمدید.
                </small>  
            </div>
            <div class="col-12 col-md-4">
                <form class="input-group">
                  <input
                    type="search"
                    class="form-control form-control-sm"
                    placeholder="جستجو"
                    aria-label="Search"
                  />
                  <div class="input-group-append">
                    <button
                      class="btn btn-sm btn-outline-primary px-3 mt-0" type="button" data-mdb-ripple-color="dark">
                      <i class="fa fa-search"></i>
                    </button>
                  </div>
                </form>        
            </div>
    </div>
  </nav>
  <nav id="main-navbar" dir="rtl" class="navbar navbar-expand-lg navbar-dark default-color-dark ">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
                            <img class="img-responsive"
                                src="{% static 'img/logo.png' %}" width="200"
                                height="66" alt="دانشکده برق و کامپیوتر"> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="{% url 'introducing' %}">معرفی دانشکده</a>
        </li>
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="{% url 'staff:index' %}">کارکنان</a>
        </li>
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="{% url 'groups:index' %}">گروه های آموزشی</a>
        </li>
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="{% url 'album:index' %}">آلبوم تصاویر</a>
        </li>
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="http://iau-tnb.ac.ir/fa/regulation">فرمها و آئین‌نامه‌ها</a>
        </li>
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="{% url 'news:index' %}">اخبار</a>
        </li>
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="{% url 'fields:index' %}">رشته ها</a>
        </li>
        <li class="nav-item border border-top-0 border-bottom-0">
          <a class="nav-link" href="{% url 'contact' %}">ارتباط با ریاست دانشکده</a>
        </li>
      </ul>
    </div>
  </nav>
  </div>
</header>
<!--Main Navigation-->
{% comment %} <div id="widget-config-modal" class="fade modal" role="dialog" tabindex="-1">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>تنظیمات ویجت</h3>
            </div>
            <div class="modal-body">
                <div class="modal-inner"></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">انصراف</button>
                <button id="submit-widget-config" type="button" class="btn btn-success">ذخیره تنظیمات</button>
            </div>
        </div>
    </div>
</div>
<header class="main-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="logo-wrapper">
                    <div class="dynamic-logo">
                        <a href="{% url 'home' %}">
                            <img class="img-responsive"
                                src="{% static 'img/logo.png' %}" width="200"
                                height="66" alt="دانشکده برق و کامپیوتر"> </a>
                        <a href="{% url 'home' %}">
                            دانشکده برق و کامپیوتر </a>
                    </div>
                </div>
            </div>
            <div class="top-bar col-sm-6">
                <div class="row">
                    <div class="col-xs-12">
                    </div>
                    <div class="search-bar col-xs-12 col-sm-8">

                        <form action="http://eng.iau-tnb.ac.ir/fa/search" method="get">
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                                <input type="text" class="form-control" name="query">
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main-menu">
        <div class="container">
            <nav id="wf7c61338fd6eb0b809394cdb96a1b0d017" class="yamm col-xs-12 col-sm-12 col-ls-9 navbar">
                <div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#wf7c61338fd6eb0b809394cdb96a1b0d017-collapse"><span class="sr-only">Toggle
                            navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span></button></div>
                <div id="wf7c61338fd6eb0b809394cdb96a1b0d017-collapse" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <ul id="wf7c61338fd6eb0b809394cdb96a1b0d018" class="navbar-nav nav" style="position:relative;">
                            <li><a
                                    href="{% url 'managers' %}">رؤسا
                                    و مدیران</a></li>
                        </ul>
                        <ul id="wf7c61338fd6eb0b809394cdb96a1b0d019" class="navbar-nav nav" style="position:relative;">
                            <li><a
                                    href="{% url 'introducing' %}">معرفی
                                    دانشکده</a></li>
                        </ul>
                        <ul id="wf7c61338fd6eb0b809394cdb96a1b0d020" class="navbar-nav nav" style="position:relative;">
                            <li><a href="http://iau-tnb.ac.ir/fa/regulation" target="_blank">فرمها و آیین نامه ها</a>
                            </li>
                        </ul>
                        <ul id="wf7c61338fd6eb0b809394cdb96a1b0d021" class="navbar-nav nav" style="position:relative;">
                            <li><a href="http://iau-tnb.ac.ir/fa">صفحه اصلی پورتال دانشگاه</a></li>
                        </ul>
                        <ul id="wf7c61338fd6eb0b809394cdb96a1b0d022" class="navbar-nav nav" style="position:relative;">
                            <li><a href="{% url 'contact' %}">تماس با ریاست دانشکده</a></li>
                        </ul>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header> {% endcomment %}